In [42]:
# doing manually and converting strings to something numerical

In [7]:
with open('One.txt') as mytext:
    a=mytext.read()

In [3]:
a

'This is a story about dogs\nour canine pets\nDogs are furry animals\n'

In [4]:
print(a)

This is a story about dogs
our canine pets
Dogs are furry animals



In [5]:
# with open('One.txt') as mytext:
#     a=mytext.readlines()

In [6]:
a

['This is a story about dogs\n',
 'our canine pets\n',
 'Dogs are furry animals\n']

In [8]:
a.lower().split()

['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

In [10]:
# array of unique words is a vocabulary
with open('One.txt') as mytext:
    words_one=mytext.read().lower().split()
    uni_words_one=set(words_one)

In [11]:
uni_words_one

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [12]:
with open('Two.txt') as mytext:
    words_two=mytext.read().lower().split()
    uni_words_two=set(words_two)

In [13]:
uni_words_two

{'a',
 'about',
 'catching',
 'fun',
 'is',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [14]:
all_uni_words=set()
all_uni_words.update(uni_words_one)

In [15]:
all_uni_words.update(uni_words_two)

In [16]:
all_uni_words

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'dogs',
 'fun',
 'furry',
 'is',
 'our',
 'pets',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [17]:
full_vocab=dict()
i=0
for word in all_uni_words:
    full_vocab[word]=i
    i=i+1

In [18]:
# order can be different
full_vocab

{'this': 0,
 'a': 1,
 'pets': 2,
 'are': 3,
 'sport': 4,
 'animals': 5,
 'dogs': 6,
 'fun': 7,
 'canine': 8,
 'furry': 9,
 'waves': 10,
 'about': 11,
 'catching': 12,
 'water': 13,
 'surfing': 14,
 'popular': 15,
 'story': 16,
 'our': 17,
 'is': 18}

In [28]:
one_freq=[0]*len(full_vocab)
two_freq=[0]*len(full_vocab)
all_uni_words=['']*len(full_vocab)

In [29]:
with open('One.txt') as f:
    one_text=f.read().lower().split()

In [30]:
# as full_vocab is a dictionary it returns index value while passing words
# increase count at the index of that particular word
for word in one_text:
    word_ind=full_vocab[word]
    one_freq[word_ind]+=1

In [31]:
one_freq

[1, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1]

In [32]:
with open('Two.txt') as f:
    two_text=f.read().lower().split()

In [33]:
for word in two_text:
    word_ind=full_vocab[word]
    two_freq[word_ind]+=1

In [34]:
two_freq

[1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 2, 1, 1, 0, 3]

In [36]:
for word in full_vocab:
    word_ind=full_vocab[word]
    all_uni_words[word_ind]=word

In [37]:
all_uni_words

['this',
 'a',
 'pets',
 'are',
 'sport',
 'animals',
 'dogs',
 'fun',
 'canine',
 'furry',
 'waves',
 'about',
 'catching',
 'water',
 'surfing',
 'popular',
 'story',
 'our',
 'is']

In [38]:
import pandas as pd

In [40]:
bow=pd.DataFrame(data=[one_freq,two_freq],columns=all_uni_words)

In [41]:
bow
# more simialr the number in words the more similar they are

this  a  pets  are  sport  animals  dogs  fun  canine  furry  waves  about  \
0     1  1     1    1      0        1     2    0       1      1      0      1   
1     1  1     0    0      1        0     0    1       0      0      1      1   

   catching  water  surfing  popular  story  our  is  
0         0      0        0        0      1    1   1  
1         1      1        2        1      1    0   3

In [43]:
# certain words are common in two documents like this,a,the and if the documents are related to same field like sports run,play will also be common which can be found in different articles of football,cricket and remove them

In [44]:
# Distinguish with Term frequency-count of words
# inverse frequency which is calculated by log of frequency of word based on all the documents
# TF_IDF

In [45]:
text=['This is a line','This is another line','Completetely different line']

In [61]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

In [63]:
# Count the frequency and create numeric vector
# cv=CountVectorizer(stop_words=['a','line'])
cv=CountVectorizer()

In [64]:
sparse_matrix=cv.fit_transform(text)

In [65]:
# sparse matrix as most of the elements will be zero so that we don't eat much of computers memory
sparse_matrix.todense()
# avoid with large data

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [66]:
# stop word->a is being removed
cv.vocabulary_

{'this': 5,
 'is': 3,
 'line': 4,
 'another': 0,
 'completetely': 1,
 'different': 2}

In [67]:
tfidf=TfidfTransformer()

In [68]:
sparse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [71]:
results=tfidf.fit_transform(sparse_matrix)
# BOW->TF-IDF

In [72]:
results

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [73]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [74]:
# This does everything in one line
from sklearn.feature_extraction.text import TfidfVectorizer

In [75]:
tv=TfidfVectorizer()

In [76]:
tv_results=tv.fit_transform(text)

In [77]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])