* Numpy is an N-dimensional array
* transform list,built in function generate from random data
* Similar to python lists

## numpy documentation

In [4]:
import numpy as np


In [2]:
mylist=[1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
myarray=np.array(mylist)

In [6]:
myarray

array([1, 2, 3])

In [7]:
type(myarray)

numpy.ndarray

In [8]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Built-In Functions

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [14]:
np.zeros((5,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.linspace(0,10,11)
# equally spaced 11 numbers between 0 and 10

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
len(np.linspace(0,5,21))

21

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

* Random distribution of numbers
* hitting tab key after dot shows the different kind of functions

In [34]:
np.random.rand(1)
# uniform distribution all numbers between 0 and 1 will have same likelihood to be picked 0 is inclusive 1 is exclusive 

array([0.25359861])

In [36]:
np.random.rand(5,2)
# we pass the shape in the parameters the random value is chosen between [0,1)

array([[0.7478994 , 0.5024771 ],
       [0.29422979, 0.88406135],
       [0.92266584, 0.76220636],
       [0.90195225, 0.94169841],
       [0.09105591, 0.8656974 ]])

In [38]:
np.random.randn(10)

array([-0.20729681, -0.33833033, -0.45572651, -1.39953793, -0.30625414,
        0.4815019 ,  0.5482361 , -1.34412918,  2.03801954,  0.60056924])

In [39]:
np.random.randn(3,7)
# It contains negative number too
# If positive int_like arguments are provided, `randn` generates an array
# of shape ``(d0, d1, ..., dn)``, filled
# with random floats sampled from a univariate "normal" (Gaussian)
# distribution of mean 0 and variance 1. A single float randomly sampled
# from the distribution is returned if no argument is provided.

array([[ 1.10900357, -0.08658613,  0.15803185, -1.22055217, -0.23638293,
         0.14043722, -0.59021488],
       [-2.54656928,  0.25713453, -0.32995976, -1.52752586,  0.57693465,
        -0.93253489,  0.23647518],
       [ 0.69538735,  0.43101038,  0.53364341, -1.17516594,  0.73783454,
        -0.62147674, -0.06458748]])

In [42]:
np.random.randint(0,101,5)
# Used to get random ages of people 

array([31, 80, 54, 24, 49])

In [43]:
np.random.randint(0,10,(2,2))

array([[5, 0],
       [1, 1]])

In [44]:
np.random.seed(42)
np.random.rand(4)

# Set a particular set of random numbers similar to check the similar set for different kinds of models or visualizations

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [45]:
np.random.seed(21)
np.random.rand(2)

array([0.04872488, 0.28910966])

In [46]:
np.random.seed(21)
np.random.rand(2)

array([0.04872488, 0.28910966])

In [47]:
np.random.rand(2)

array([0.72096635, 0.02161625])

In [48]:
arr=np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [52]:
ranarr=np.random.randint(0,101,10)
ranarr

array([ 60,  98,  74,  72,  63,  44,  61,  48, 100,  84])

In [54]:
ranarr.max()

100

In [55]:
ranarr.min()

44

In [56]:
ranarr.argmax()
#  To return the index position of the maximum number

8

In [57]:
ranarr.argmin()

5

In [59]:
ranarr.dtype
# dtype and shape which are without brackets () are attributes but not function calls

dtype('int32')

In [60]:
ranarr.shape

(10,)

In [62]:
a=ranarr.reshape(5,2)
a

array([[ 60,  98],
       [ 74,  72],
       [ 63,  44],
       [ 61,  48],
       [100,  84]])

In [64]:
a.shape

(5, 2)

In [69]:
a.reshape(10,)

array([ 60,  98,  74,  72,  63,  44,  61,  48, 100,  84])

In [70]:
a.reshape(1,10)

array([[ 60,  98,  74,  72,  63,  44,  61,  48, 100,  84]])

In [72]:
myarray=np.linspace(0,10,101)

## Indexing and selection

In [75]:
ap=np.arange(0,11)

In [76]:
ap

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
ap[8]

8

In [81]:
ap[1:5]

array([1, 2, 3, 4])

In [82]:
ap[:5]

array([0, 1, 2, 3, 4])

In [83]:
ap[5:]

array([ 5,  6,  7,  8,  9, 10])

In [84]:
ap[0:5]=100

In [85]:
ap

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [86]:
ap=np.arange(0,11)

In [89]:
slice=ap[0:5]
slice

array([0, 1, 2, 3, 4])

In [90]:
ap

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
slice[:]=999
slice

array([999, 999, 999, 999, 999])

In [92]:
ap

array([999, 999, 999, 999, 999,   5,   6,   7,   8,   9,  10])

In [93]:
ap_copy=ap.copy()

In [96]:
ap_copy[:]=100
ap_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [97]:
ap

array([999, 999, 999, 999, 999,   5,   6,   7,   8,   9,  10])

In [100]:
ap_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
ap_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
ap_2d[0]

array([1, 2, 3])

In [102]:
ap_2d[2]

array([7, 8, 9])

In [103]:
ap_2d[1][1]

5

In [104]:
ap_2d[1,1]

5

In [106]:
ap_2d[2:]
# last column

array([[7, 8, 9]])

In [107]:
ap_2d[:2]
# uptil last row

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
ap_2d[:2,1:]
# uptil second row and after first column

array([[2, 3],
       [5, 6]])

In [109]:
ap_2d[:2,:1]

array([[1],
       [4]])

In [110]:
ad=np.arange(1,11)
ad

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
ad>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [112]:
bool_ad=ad>4

In [113]:
ad[bool_ad]

array([ 5,  6,  7,  8,  9, 10])

In [114]:
ad[ad>4]

array([ 5,  6,  7,  8,  9, 10])

In [117]:
ad[ad==6]

array([6])

In [119]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

total_rolls_over_two = len(dice_rolls[dice_rolls>2])
total_rolls_over_two

19

In [5]:
ak=np.arange(0,10)

In [6]:
ak

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
ak+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
ak-ak

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
ak/ak
# Zero devision at index 1

C:\Users\rajsh\AppData\Local\Temp/ipykernel_17216/2050970589.py:1: RuntimeWarning: invalid value encountered in true_divide
  ak/ak


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [12]:
np.sqrt(ak)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [13]:
np.sin(ak)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [14]:
np.log(ak)
# Taking log of Zero

C:\Users\rajsh\AppData\Local\Temp/ipykernel_17216/1618494853.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(ak)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [15]:
ak.mean()

4.5

In [16]:
ak.var()

8.25

In [17]:
ak.std()

2.8722813232690143

In [19]:
bp=np.arange(0,25)

In [23]:
c=bp.reshape(5,5)

In [24]:
c.shape

(5, 5)

In [25]:
c.sum(axis=0)
# across columns

array([50, 55, 60, 65, 70])

In [26]:
c.sum(axis=1)
# across rows

array([ 10,  35,  60,  85, 110])

In [27]:
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

account_total =  account_transactions.sum()
account_total

2720